

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven_version:
    uses: sfuhrm/github_workflows/.github/workflows/maven-expression.yml@main
    permissions:
      contents: read
    with:
      java_version: 25
      expression: project.version
  call-workflow-passing-data:
    needs: maven_version
    uses: sfuhrm/github_workflows/.github/workflows/maven.yml@main
    permissions:
      contents: read
    with:
      java_version: "[ \"25\" ]"
      artifact_name: build
      artifact_path: radiorecorder/target/radiorecorder-${{ needs.maven_version.outputs.expression_value }}.jar
